version: "3"
services:
  nginx:
    build:
      dockerfile: ./Nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
  apache:
    build: ./Apach
    volumes:
      - ./Apach/pages:/var/www/html/
      - ./Apach/deg.conf:/etc/apache2/sites-available/deg.conf
    ports:
      - "8081:80"
    links:
      - db
      - nginx
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./bd/init.sql:/docker-entrypoint-initdb.d/init.sql"
networks:
  internal:
    driver: bridge